# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=50)),
                ('buyer_email', models.EmailField(default='buyer@gmail.com', max_length=30)),
                ('buyer_password', models.CharField(default='buyer_password', max_length=30)),
                ('buyer_address', models.CharField(max_length=200)),
                ('buyer_contactNo', models.CharField(max_length=10)),
                ('buyer_regNo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(default='user@gmail.com', max_length=30)),
                ('user_password', models.CharField(default='user_password', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TenderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_name', models.CharField(max_length=100)),
                ('product_details', models.CharField(max_length=500)),
                ('estimated_cost', models.IntegerField(default=0)),
                ('tender_deadline', models.IntegerField(default=0)),
                ('tender_status', models.IntegerField(default=0)),
                ('win_quote', models.IntegerField(default=0)),
                ('win_vid', models.IntegerField(default=0)),
                ('buyer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenderApp.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='TenderQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_quotation', models.IntegerField(default=0)),
                ('tender1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenderApp.TenderInfo')),
                ('vendor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenderApp.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50)),
                ('vendor_email', models.EmailField(default='vendor@gmail.com', max_length=30)),
                ('vendor_password', models.CharField(default='vendor_password', max_length=30)),
                ('vendor_address', models.CharField(max_length=200)),
                ('vendor_contactNo', models.CharField(max_length=10)),
                ('vendor_feedback', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VendorFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_feedback', models.IntegerField(default=0)),
                ('buyer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenderApp.Buyer')),
                ('vendor2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenderApp.Vendor')),
            ],
        ),
    ]
