# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderinfo',
            name='tender_deadline',
            field=models.DateField(blank=True),
        ),
    ]
